import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { auth } from '../../../shared/util/firebase';
import { getAuth, GoogleAuthProvider, signInWithPopup } from 'firebase/auth';
import React from 'react';

const provider = new GoogleAuthProvider()
provider.setCustomParameters({
  prompt: "select_account"
})

export default function Home() {
  const [message, setMessage] = React.useState('Welcome');

  return (
    <>
      <Head>
        <title>Admin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <h1>{message}</h1>
        </div>
        <button
          onClick={e => {
            signInWithPopup(auth, provider)
              .then((result) => {
                // This gives you a Google Access Token. You can use it to access the Google API.
                const user = result.user;
                console.log(user.email);
                // ...
              }).catch((error) => {
                // Handle Errors here.
                console.error(error);
                const errorCode = error.code;
                const errorMessage = error.message;
                // The email of the user's account used.
                const email = error.customData.email;
                // The AuthCredential type that was used.
                const credential = GoogleAuthProvider.credentialFromError(error);
                // ...
              });
          }}
        >Login</button>
      </main>
    </>
  )
}
