import Head from 'next/head'
import React, { useEffect } from 'react';
import axios, { AxiosError } from 'axios';
import firebase, { auth, Auth } from '@shared/util/firebase'
import useUser from '@/hooks_etc/useUser';

export default function Home() {
  const user = useUser();
  const provider = React.useMemo(() => new Auth.GoogleAuthProvider(), []);

  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <h1>{user?.email ?? 'logged out'}</h1>
        </div>
        <button
          onClick={e => {
            Auth.signInWithPopup(auth, provider)
          }}
        >Login</button>
      </main>
    </>
  )
}
